### ISSUE TITLE
Demonstrate usage of variables

### ISSUE THREAD

**Issue by retzkek** [grafana/simple-datasource#3]
Please demonstrate the idiomatic way of using template variables. Existing datasources (including the "reactified" builtins) use `templateSrv`, which doesn't appear to be in `@grafana/ui` (yet?).  

Thank you!

**Comment by retzkek** [comment]
So, for what it's worth, I wrote a simple datasource based on this that uses `templateSrv` as well as `backendSrv`: https://github.com/fifemon/graphql-datasource  (functional, but WIP).

**Comment by Biglr** [comment]
I'd like to see that as well.

Especially some examples for how to handle custom headers and how to access the secure JSON properties... I've currently got the problem that as soon as I set a custom header, the request just fails with the Chrome error message `net::ERR_FAILED` which is very strange. If I remove the headers, the request is carried out as expected but fails with a 401 error from the API (the header would contain the API Key).

**Comment by marcusolsson** [comment]
This is the template that everyone get when starting a new plugin. I'd like to keep features to a minimum, to make it a good starting point. 

I think we should improve the docs rather than add it to this repository. If you think a more detailed example is warranted, please add it to the [grafana-plugin-examples](https://github.com/grafana/grafana-plugin-examples) repository.

For more information on how to use variables in your plugin, check out [Add support for variables](https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/).
